name: Random Pinger

on:
  schedule:
    - cron: "*/2 * * * *"   # run every 2 minutes
  workflow_dispatch:        # allow manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Run Pinger
        run: node ping.js

      - name: Commit Log
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ping-log.txt
          git commit -m "Update ping log [skip ci]" || echo "No changes to commit"
          git push
